### ISSUE TITLE
Statusbar appears after hiding

### ISSUE THREAD

**Issue by stereodenis** [NishanthShankar/react-native-android-statusbar#12]
1. Hide statusbar
2. Try to open statusbar by swiping down from top
3. Statusbar appears

maybe it is possible to get event and hide again?

**Comment by NishanthShankar** [comment]
Will look into this

**Comment by Amurmurmur** [comment]
@NishanthShankar @stereodenis
Whenever you push the app into the background (for example you switch between the apps) the StatusBar appears again, on app resume.

So I guess the best practise would be to hide the statusbar or manipulate the color through a native approach via https://developer.android.com/training/material/theme.html 
For now, seems like this package hasnt been supported for a while...

Update:
My bad, its actually supported by react-native now.
No need for this module.

Just simply do:
```
import {StatusBar} from 'react-native'
StatusBar.setHidden(true)
```
in your index.android.js

Hope this helps 👍
