### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by gnvcor** [NishanthShankar/react-native-android-statusbar#15]
Greetings! When registering module MainActivity error appears:

MainActivity.java:29: error: method does not override or implement a method from a supertype
     @Override
     ^
1 error
: App: compileDebugJavaWithJavac FAILED

Version react native 0.30.0.
Prompt please, in what could be the problem?

**Comment by joostlawerman** [comment]
Simply remove the @Override and it sould work.

**Comment by gnvcor** [comment]
If remove the @Override, then the project is built correctly. But when I import the react-native-android-statusbar (`import StatusBarAndroid from 'react-native-android-statusbar';`), the StatusBarAndroid - undefined.

**Comment by NishanthShankar** [comment]
Please check current documentation
