### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by mallikarjunakp** [NishanthShankar/react-native-android-statusbar#17]
/MainActivity.java:41: error: constructor StatusBarPackage in class StatusBarPackage cannot be applied to given types;
        new StatusBarPackage(this)
        ^
  required: no arguments
  found: MainActivity
  reason: actual and formal argument lists differ in length
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

I have followed all the instruction of installing.

`import me.neo.react.StatusBarPackage;`
.
.
.
`@Override`
 `protected List<ReactPackage> getPackages() {`
  `return Arrays.<ReactPackage>asList(`
   `new MainReactPackage(),`
    `new StatusBarPackage(this)`
     `);`
    `}`
.
.
.

**Comment by CharlesJQuarra** [comment]
I'm having the same problem trying to build https://github.com/react-native-material-design/demo-app

**Comment by Amurmurmur** [comment]
Same issue here :/
React-native v0.32

**Comment by maraujop** [comment]
This probably fixes your issue
https://github.com/NishanthShankar/react-native-android-statusbar/pull/18

In RN >= 0.30 you no longer need to pass `this` to the package

Cheers,
Miguel

**Comment by Kepro** [comment]
works for me after remove this
