### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by waynexu110** [NishanthShankar/react-native-android-statusbar#19]
Hi, NishanthShankar

After install and react-native run-android,
i got undefined is not an object (a.showStatusBar).

    StatusBarAndroid.showStatusBar();
    StatusBarAndroid.setHexColor('#303F9F'); 

where should i place this code with react-native  "0.39.2" and android 4.4
tks!

**Comment by tywhang** [comment]
Are you sure you did ALL the steps?

I first ran into the same issue as you until I realized that there are actually 2 things you need to do in `MainApplication.java`.

Hope this helps!

**Comment by NishanthShankar** [comment]
Closing this issue. Please check README for further assistance
