### ISSUE TITLE
Multiple @Override decorators(?) not working for RN 0.44.0

### ISSUE THREAD

**Issue by dazziola** [NishanthShankar/react-native-android-statusbar#20]
public class MainActivity extends ReactActivity {

        @Override
        protected String getMainComponentName() {
            return "TonyAppReact";
        }
     
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }
     
        @Override
        protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new StatusBarPackage(this)
          );
        }
    }

Having multiple Override decorators is throwing errors when trying to build using Android Studio or RN CLI.

`Error:(23, 5) error: method does not override or implement a method from a supertype`

Any ideas how to fix this? I've removed the Override decorators bar the first one and I get rid of that error, but then run into an issue that seems to pertain to the `this` argument in the StatusBarPackage instance creation.

`Error:(30, 9) error: constructor StatusBarPackage in class StatusBarPackage cannot be applied to given types;
required: no arguments
found: MainActivity
reason: actual and formal argument lists differ in length`

**Comment by sahil-innostax** [comment]
facing the same issue

**Comment by NishanthShankar** [comment]
6919cbe2bb204da37b0cfccfd7952d6c66e46b12 has fixed this. Will release an update soon

**Comment by muhammadsr** [comment]
The fix for this is in `master`. Can someone make a new release please
