### ISSUE TITLE
Configure MainActivity.java

### ISSUE THREAD

**Issue by TheodorBotnaru** [NishanthShankar/react-native-android-statusbar#9]
Hello,

Thank you for sharing your work.
I am not able to properly configure MainActivity.java.
That is because the MainActivity class generated by react native does not extends Activity, but extands ReactActivity.

And after pasting your code, the code does not compile any more.
I just don't have variables like mReactInstanceManager and mReactRootView.

This is how my MainActivity.java class was generated:

package com.company.projectname;

import com.facebook.react.ReactActivity;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

public class MainActivity extends ReactActivity {

```
/**
 * Returns the name of the main component registered from JavaScript.
 * This is used to schedule rendering of the component.
 */
@Override
protected String getMainComponentName() {
    return "projectname";
}

/**
 * Returns whether dev mode should be enabled.
 * This enables e.g. the dev menu.
 */
@Override
protected boolean getUseDeveloperSupport() {
    return BuildConfig.DEBUG;
}
```

   /**
- A list of packages used by the app. If the app uses additional views
- or modules besides the default ones, add more packages here.
  */
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage());
  }
  }

Sorry if I am missing something obvious.

**Comment by TheodorBotnaru** [comment]
Hello,

I found the solution myself and I will write it here in case anyone needs it.
In MainActivity class that was generated, i have a method:
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage());
    }
that I can change to load StatusBarPackage
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new StatusBarPackage(this)); <-- added here
    }

**Comment by NishanthShankar** [comment]
Hi, I am sorry I missed this issue, but I have explained the same in my README file.
